version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile-nginx
    ports:
      - '80:80'
    networks:
      - network1
    volumes:
      - ../:/code
      - ./nginx/logs:/var/log/nginx
  php7.0:
    build:
      context: ./php
      dockerfile: dockerfile-php7.0
    networks:
      - network1
    volumes:
      - ../:/code
  php7.4:
    build:
      context: ./php
      dockerfile: dockerfile-php7.4
    networks:
      - network1
    volumes:
      - ../:/code
  mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile-mysql
    ports:
      - '3306:3306'
    networks:
      - network1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
  memcached:
    image: memcached:1.5
#    ports:
#      - '11211:11211'
    networks:
      - network1

networks:
  network1:
    driver: bridge
