version: '3'
services:
  nginx:
    image: docker-dev-nginx:1.0.0
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - network1
    volumes:
      - ../:/code
      - ./nginx/logs:/var/log/nginx
  php7.0:
    image: registry.cn-shanghai.aliyuncs.com/luxiaochen/docker-dev-php7.0:1.0.4
    networks:
      - network1
    volumes:
      - ../:/code
    environment:
      - XDEBUG_REMOTE_HOST=192.168.1.14
  php7.4:
    image: registry.cn-shanghai.aliyuncs.com/luxiaochen/docker-dev-php7.4:1.0.5
    networks:
      - network1
    volumes:
      - ../:/code
    environment:
      - XDEBUG_REMOTE_HOST=192.168.1.14
  mysql:
    image: docker-dev-mysql:1.0.0
    build:
      context: ./mysql
      dockerfile: mysql.dockerfile
    ports:
      - '3306:3306'
    networks:
      - network1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
  memcached:
    image: memcached:1.5.22
#    ports:
#      - '11211:11211'
    networks:
      - network1
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    networks:
      - network1
  tomcat:
    image: tomcat:9.0.31-jdk13-openjdk-oracle
    ports:
      - '8080:8080'
    networks:
      - network1
networks:
  network1:
    driver: bridge
volumes:
  mysql_data:
